language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ibupatra/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ibupatra/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: ""
  app: "docker-react"
  env: ""
  bucket_name: ""
  bucket_path: ""
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


